spring:
 application:
  name: api-gateway

 cloud:
  loadbalancer:
   enabled: true
  gateway:
   server:
    webflux:
     routes:
      - id: msv-huespedes #aqui va el nombre del msv
        uri: lb://msv-huespedes #aqui va el nombre del msv
        predicates:
         - Path=/api/huespedes/** #Esta es la ruta a la cual se accedera
        filters:
         - StripPrefix=2
      - id: msv-proveedores #aqui va el nombre del msv
        uri: lb://msv-proveedores #aqui va el nombre del msv
        predicates:
         - Path=/api/proveedores/** #Esta es la ruta a la cual se accedera
        filters:
         - StripPrefix=2
      - id: msv-productos #aqui va el nombre del msv
        uri: lb://msv-productos #aqui va el nombre del msv
        predicates:
         - Path=/api/productos/** #Esta es la ruta a la cual se accedera
        filters:
         - StripPrefix=2
server:
 port: 8090

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
