spring:
 application:
  name: api-gateway

 security:
  oauth2:
   resourceserver:
    jwt:
     jwk-set-uri: http://localhost:9000/oauth2/jwks #esta configuracion esta en la documentacion

 cloud:
  loadbalancer:
   enabled: true
  gateway:
   server:
    webflux:
     routes:
      - id: mvs-habitaciones
        uri: lb://mvs-habitaciones
        predicates:
         - Path=/api/habitaciones/** 
        filters:
         - StripPrefix=2
      - id: msv-huespedes
        uri: lb://msv-huespedes
        predicates:
         - Path=/api/huespedes/** 
        filters:
         - StripPrefix=2
      - id: msv-reserva
        uri: lb://msv-resera
        predicates:
         - Path=/api/reserva/**
        filters:
         - StripPrefix=2


server:
 port: 8090

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
